# Generated by Django 6.0.1 on 2026-03-09 04:53

import apps.diagnostics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='medical_records/heatmaps/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='document',
            field=models.FileField(upload_to='medical_records/%Y/%m/%d/', validators=[apps.diagnostics.models.validate_medical_file]),
        ),
    ]
